"""Room type and flow-state constants for dungeon progression."""

ROOM_ENCOUNTER = "ENCOUNTER"
ROOM_BOSS_PLACEHOLDER = "BOSS_PLACEHOLDER"
ROOM_DUNGEON_CLEAR = "DUNGEON_CLEAR"

ROOM_ACTIVE = "ACTIVE"
ROOM_CLEARED = "CLEARED"
ROOM_COMPLETE = "COMPLETE"
