"""Room type and flow-state constants for dungeon progression."""

ROOM_ENCOUNTER = "ENCOUNTER"
ROOM_BOSS_ENCOUNTER = "BOSS_ENCOUNTER"
ROOM_DUNGEON_CLEAR = "DUNGEON_CLEAR"

ROOM_ACTIVE = "ACTIVE"
ROOM_CLEARED = "CLEARED"
ROOM_REWARD = "REWARD"
ROOM_COMPLETE = "COMPLETE"
