"""Prototype elite/boss tuning.

This file contains neutral mechanical values only. Final boss identity,
fantasy, named attacks, and visual direction still require user approval.
"""

ELITE_ENEMY_CONFIG = {
    "label": "ELITE ENEMY",
    "width": 74,
    "height": 140,
    "max_health": 380,
    "hurt_flash_duration": 0.12,
    "knockback_friction": 2100,
    "chase_speed": 78,
    "attack_start_distance": 126,
    "telegraph_duration": 0.86,
    "attack_duration": 0.30,
    "attack_cooldown": 1.65,
    "attack_damage": 14,
    "attack_range": 102,
    "attack_height": 78,
    "attack_knockback": 340,
    "retreat_duration": 0.34,
    "retreat_speed": 58,
    "attack_hitstop": 0.050,
    "attack_shake_duration": 0.13,
    "attack_shake_strength": 4,
    "recovery_duration": 0.78,
    "stagger_duration": 0.44,
    "body_color": (165, 58, 84),
    "hurt_color": (255, 226, 236),
    "defeated_color": (62, 38, 50),
    "telegraph_color": (255, 214, 115),
    "attack_color": (255, 105, 95),
    "telegraph_pulse_speed": 7,
    "recoil_outline_color": (95, 32, 52),
    "hurt_reaction_duration": 0.09,
    "hurt_reaction_heavy_bonus": 0.03,
    "punish_window_duration": 0.58,
    "recovery_flash_duration": 0.46,
    "stagger_emphasis_duration": 0.20,
    "post_stagger_recovery_duration": 0.24,
    "reaction_recoil_pixels": 5,
    "recovery_tint_color": (255, 218, 170),
    "punish_outline_color": (255, 238, 180),
    "stagger_emphasis_color": (255, 246, 210),
}

BOSS_SKILL_CONFIG = {
    "cooldown": 6.5,
    "initial_cooldown": 3.5,
    "initial_decision_delay": 2.0,
    "telegraph_duration": 0.82,
    "active_duration": 0.18,
    "recovery_duration": 0.82,
    "skill_range": 220,
    "skill_height": 42,
    "damage": 20,
    "knockback": 320,
    "range_tolerance": 70,
    "post_skill_decision_delay": 1.25,
    "interrupt_decision_delay": 1.0,
}

SOLO_BOSS_CONFIG = {
    "label": "SOLO BOSS",
    "max_health": 260,
    "attack_range": 74,
    "attack_start_distance": 94,
    "skill_range": 150,
    "skill_height": 38,
    "skill_damage": 18,
}
