"""Prototype elite/boss tuning.

This file contains neutral mechanical values only. Final boss identity,
fantasy, named attacks, and visual direction still require user approval.
"""

ELITE_ENEMY_CONFIG = {
    "label": "ELITE ENEMY",
    "width": 74,
    "height": 140,
    "max_health": 380,
    "hurt_flash_duration": 0.12,
    "knockback_friction": 2100,
    "chase_speed": 78,
    "attack_start_distance": 126,
    "telegraph_duration": 0.86,
    "attack_duration": 0.30,
    "attack_cooldown": 1.65,
    "attack_damage": 14,
    "attack_range": 102,
    "attack_height": 78,
    "attack_knockback": 340,
    "retreat_duration": 0.34,
    "retreat_speed": 58,
    "attack_hitstop": 0.050,
    "attack_shake_duration": 0.13,
    "attack_shake_strength": 4,
    "recovery_duration": 0.78,
    "stagger_duration": 0.44,
    "body_color": (165, 58, 84),
    "hurt_color": (255, 226, 236),
    "defeated_color": (62, 38, 50),
    "telegraph_color": (255, 214, 115),
    "attack_color": (255, 105, 95),
    "telegraph_pulse_speed": 7,
    "recoil_outline_color": (95, 32, 52),
    "hurt_reaction_duration": 0.09,
    "hurt_reaction_heavy_bonus": 0.03,
    "punish_window_duration": 0.58,
    "recovery_flash_duration": 0.46,
    "stagger_emphasis_duration": 0.20,
    "post_stagger_recovery_duration": 0.24,
    "reaction_recoil_pixels": 5,
    "recovery_tint_color": (255, 218, 170),
    "punish_outline_color": (255, 238, 180),
    "stagger_emphasis_color": (255, 246, 210),
}

BOSS_SKILL_CONFIG = {
    "cooldown": 6.5,
    "initial_cooldown": 3.5,
    "initial_decision_delay": 2.0,
    "telegraph_duration": 0.82,
    "active_duration": 0.18,
    "recovery_duration": 0.82,
    "skill_range": 220,
    "skill_height": 42,
    "damage": 20,
    "knockback": 320,
    "range_tolerance": 70,
    "post_skill_decision_delay": 1.25,
    "interrupt_decision_delay": 1.0,
}

SOLO_BOSS_CONFIG = {
    "label": "SOLO BOSS",
    "max_health": 260,
    "attack_range": 74,
    "attack_start_distance": 94,
}

# Solo-only user-approved combo structure. Dungeon keeps the neutral Phase 31
# placeholder controller unchanged.
SOLO_BOSS_COMBO_CONFIG = {
    "max_energy": 100,
    "start_energy": 0,
    "dealt_hit_energy_gain": 9,
    "hurt_energy_gain": 3,
    "initial_cooldown": 2.0,
    "decision_delay": 0.75,
    "max_repeat_count": 2,
    "major_skill_spacing": 3.2,
    "final_lockout": 14.0,
    "final_min_prior_skills": 3,
    "final_range": 118,
    "skill_range": 150,
    "skill_height": 58,
    "knockback": 185,
    "stun_duration": 0.62,
    "skill_lock_duration": 2.0,
    "base_hit_damage": (6, 8, 10),
    "skill_1": {
        "energy_cost": 35,
        "frames": (0, 1, 2),
        "weight": 5,
        "telegraph_duration": 0.48,
        "hit_durations": (0.20, 0.20, 0.24),
        "group_pause_after_hits": {},
        "recovery_duration": 0.68,
        "post_decision_delay": 0.78,
        "cooldown_gate": 2.4,
        "damage_multiplier": 1,
        "stun_hits": (),
        "skill_lock_hits": (),
    },
    "skill_2": {
        "energy_cost": 65,
        "frames": (3, 4, 5),
        "weight": 3,
        "telegraph_duration": 0.60,
        "hit_durations": (0.14, 0.14, 0.18),
        "group_pause_after_hits": {},
        "recovery_duration": 1.0,
        "post_decision_delay": 1.15,
        "cooldown_gate": 4.4,
        "damage_multiplier": 2,
        "stun_hits": (),
        "skill_lock_hits": (),
    },
    "final_skill": {
        "energy_cost": 100,
        "frames": (0, 1, 2, 3, 4, 5),
        "weight": 1,
        "telegraph_duration": 0.92,
        "hit_durations": (0.18, 0.18, 0.22, 0.18, 0.18, 0.26),
        "group_pause_after_hits": {3: 0.32},
        "recovery_duration": 1.55,
        "post_decision_delay": 2.2,
        "cooldown_gate": 12.0,
        "damage_multiplier": 3,
        "stun_hits": (3, 6),
        "skill_lock_hits": (3, 6),
    },
}
