"""Prototype Solo and Dungeon mode tuning.

These values describe existing flow only. New modes and major direction
changes still require user approval.
"""

# Dungeon encounter pacing
ENCOUNTER_WAVE_DELAY = 1.10
ENCOUNTER_STATUS_Y = 126
ENCOUNTER_WAVE_BANNER_DURATION = 1.35
ENCOUNTER_WAVE_BANNER_FADE_TIME = 0.40
ENCOUNTER_WAVE_ACTIVATION_DELAY = 0.80
ENCOUNTER_ATTACK_SWAP_DELAY = 0.28
ENCOUNTER_RECOVERY_TEXT_Y = 166
ENCOUNTER_PRESSURE_LEAD_TIME = 0.18
ENCOUNTER_SPAWN_STAGGER = 0.12
ENCOUNTER_ENTRANCE_OFFSET = 56
ENCOUNTER_ENTRANCE_MOVE_SPEED = 260
ENCOUNTER_ENTRANCE_PAUSE = 0.16
ENEMY_SPACING_MIN_DISTANCE = 92
ENEMY_SPACING_PULL_STRENGTH = 4.6
ENEMY_SPACING_SEPARATION_FORCE = 5.0
ENEMY_SPACING_MAX_STEP = 190
ENEMY_FLANK_NEAR_OFFSET = 180
ENEMY_FLANK_FAR_OFFSET = 320
PRESSURE_INDICATOR_COLOR = (255, 236, 160)
PRESSURE_ACTIVE_COLOR = (255, 192, 120)
# Solo-only prototype tuning
SOLO_PLAYER_SPAWN_X = 180
SOLO_ENEMY_RIGHT_OFFSET = 280
SOLO_PLAYER_ATTACK_RANGES = {1: 54, 2: 60, 3: 70}
SOLO_COMBO_BURST_ENERGY_COST = 40
SOLO_COMBO_BURST_GAP_DURATION = 0.045
SOLO_MAX_ENERGY = 100
SOLO_START_ENERGY = 50
SOLO_ATTACK_ENERGY_GAIN = 8
SOLO_FINISHER_ENERGY_GAIN = 12
SOLO_HURT_ENERGY_GAIN = 3
SOLO_ENERGY_COLOR = (110, 195, 255)
SOLO_ENERGY_BG = (25, 38, 56)
